schema: http://localhost:8080/graphql
documents: graphql/queries/**/*.gql

extensions:
  codegen:
    generates:
      ./graphql/generated.ts:
        plugins:
          - typescript
          - typescript-operations
          - typed-document-node
