fragment User on Account {
   id
   email
   username
   email
   avatar
}

fragment Self on Account {
   ...User
   permissions
}

query me {
   me {
      ...Self
   }
}

query getAccounts($pagination: Pagination, $filter: AccountFilter) {
   accounts(pagination: $pagination, filter: $filter) {
      nodes {
         ...User
      }
      pageInfo {
         ...PageInfo
      }
   }
}
