fragment Pos on Point {
   x
   y
   z
}

fragment MapLocation on Location {
   id
   name
   slug
   pos {
      ...Pos
   }
}

query getLocations {
   locations {
      totalCount
      nodes {
         ...MapLocation
      }
   }
}

query getLocation($slug: String!) {
   location: locationBySlug(slug: $slug) {
      ...MapLocation
      tales {
         totalCount
         nodes {
            id
            title
            text
         }
      }
   }
}

mutation createLocation($input: CreateLocationInput!) {
   createLocation(input: $input)
}
