fragment PlaceProposalPreview on PlaceProposal {
   ...WithTime
   submitter {
      ...User
   }
   draft {
      id
      name
      original {
         id
         name
      }
   }
}

query getPlaceProposals($pagination: Pagination) {
   connection: placeProposals(pagination: $pagination) {
      totalCount
      nodes {
         ...PlaceProposalPreview
      }
      pageInfo {
         ...PageInfo
      }
   }
}

query getPlaceProposal($draft: Int!) {
   proposal: placeProposal(draftId: $draft) {
      ...PlaceProposalPreview
      draft {
         pos {
            ...Pos
         }
      }
   }
}

mutation approvePlace($draft: Int!) {
   converted: approvePlace(draftId: $draft)
}

mutation refusePlace($draft: Int!) {
   converted: refusePlace(draftId: $draft)
}
