fragment LocationSummary on AbstractLocation {
   ...MapLocation
   ... on Location {
      tales {
         totalCount
      }
   }
}

fragment Location on Location {
   ...LocationSummary
   tales {
      totalCount
      nodes {
         id
         title
         text
      }
   }
}

query getLocations($pagination: Pagination) {
   connection: locations(pagination: $pagination) {
      totalCount
      nodes {
         ...LocationSummary
      }
      pageInfo {
         ...PageInfo
      }
   }
}

query getLocation($slug: String!) {
   location: locationBySlug(slug: $slug) {
      ...Location
   }
}

query getLocationById($id: Int!) {
   location: location(id: $id) {
      ...Location
   }
}

mutation createLocation($input: CreateLocationInput!) {
   created: createLocation(input: $input) {
      id
      slug
   }
}

mutation modifyLocation($id: Int!, $input: ModifyLocationInput!) {
   created: modifyLocation(id: $id, input: $input) {
      id
      slug
   }
}
