fragment Pos on Point {
   x
   y
   z
}

fragment FlatPos on FlatPoint {
   x
   z
}

fragment MapLocation on AbstractLocation {
   id
   name
}

fragment MapPlace on AbstractPlace {
   ...MapLocation
   pos {
      ...Pos
   }
   ... on Place {
      slug
   }
}

fragment MapArea on AbstractArea {
   ...MapLocation
   points {
      ...FlatPos
   }
   ... on Area {
      slug
   }
}

fragment World on World {
   id
   name
}

query mapLocations {
   places {
      totalCount
      nodes {
         ...MapPlace
      }
   }
   areas {
      totalCount
      nodes {
         ...MapArea
      }
   }
}

query getWorlds {
   worlds {
      ...World
   }
}
