fragment Pos on Point {
  x
  y
  z
}

fragment MapPOI on POI {
  id
  name
  slug
  pos {
    ...Pos
  }
}

query getPois {
  pois {
    ...MapPOI
  }
}

query getPoi($slug: String!) {
  poi: poiBySlug(slug: $slug) {
    ...MapPOI
    tales {
      title
      text
    }
  }
}

mutation createPoi($input: CreatePOIInput!) {
  createPoi(input: $input)
}
