fragment Pos on Point {
  x
  y
  z
}

fragment MapPOI on POI {
  id
  name
  slug
  pos {
    ...Pos
  }
}

query getPois {
  pois {
    ...MapPOI
  }
}

mutation createPoi($input: CreateInput!) {
  createPoi(input: $input)
}
