query relationsGraph {
   tales {
      nodes {
         id
         authorId
         title
         places {
            nodes {
               id
            }
         }
         areas {
            nodes {
               id
            }
         }
         species {
            nodes {
               id
            }
         }
         characters {
            nodes {
               id
            }
         }
      }
   }
   places {
      nodes {
         id
         authorId
         name
      }
   }
   areas {
      nodes {
         id
         authorId
         name
      }
   }
   species: speciess {
      nodes {
         id
         authorId
         name
      }
   }
   characters {
      nodes {
         id
         authorId
         speciesId
         name
      }
   }
}
