fragment TaleSummary on AbstractTale {
   id
   title
   ... on Tale {
      locations {
         totalCount
      }
   }
   ... on TaleDraft {
      locations {
         totalCount
      }
   }
}

fragment Tale on AbstractTale {
   ...TaleSummary
   text
   ... on Tale {
      locations {
         nodes {
            ...MapLocation
         }
      }
   }
   ... on TaleDraft {
      locations {
         nodes {
            ...MapLocation
         }
      }
   }
}

query getTales($pagination: Pagination) {
   connection: tales(pagination: $pagination) {
      totalCount
      nodes {
         ...TaleSummary
      }
      pageInfo {
         ...PageInfo
      }
   }
}

query getTale($id: Int!) {
   tale(id: $id) {
      ...Tale
   }
}

mutation createTale($input: CreateTaleInput!, $locations: [Int!]) {
   created: createTale(input: $input, locations: $locations)
}
