fragment Summary on Tale {
  id
  title
}

fragment Lore on Tale {
  ...Summary
  text
}

query getTales($offset: Long) {
  tales(pagination: { offset: $offset }) {
    totalCount
    nodes {
      ...Summary
    }
  }
}

query getTale($id: Int!) {
  tale(id: $id) {
    ...Lore
  }
}

mutation createTale($input: CreateTaleInput!, $locations: [Int!]) {
  createTale(input: $input, locations: $locations)
}
