query getTaleDrafts($pagination: Pagination) {
   connection: taleDrafts(pagination: $pagination) {
      totalCount
      nodes {
         ...TaleSummary
      }
      pageInfo {
         ...PageInfo
      }
   }
}

query getTaleDraft($id: Int!) {
   taleDraft(id: $id) {
      ...Tale
   }
}

mutation createTaleDraft($input: CreateTaleInput!, $locations: [Int!]) {
   created: createTaleDraft(input: $input, locations: $locations)
}
