fragment TaleProposalPreview on TaleProposal {
   ...WithTime
   submitter {
      ...User
   }
   draft {
      id
      title
      original {
         id
         title
      }
   }
}

query getTaleProposals($pagination: Pagination) {
   connection: taleProposals(pagination: $pagination) {
      totalCount
      nodes {
         ...TaleProposalPreview
      }
      pageInfo {
         ...PageInfo
      }
   }
}

query getTaleProposal($draft: Int!) {
   proposal: taleProposal(draftId: $draft) {
      ...TaleProposalPreview
      draft {
         text
      }
   }
}

mutation approveTale($draft: Int!) {
   converted: approveTale(draftId: $draft)
}

mutation refuseTale($draft: Int!) {
   converted: refuseTale(draftId: $draft)
}
