fragment Summary on Tale {
   id
   title
}

fragment Lore on Tale {
   ...Summary
   text
}

query getTales($pagination: Pagination) {
   connection: tales(pagination: $pagination) {
      totalCount
      nodes {
         ...Summary
      }
      pageInfo {
         hasPreviousPage
         hasNextPage
         startCursor
         endCursor
         offset
      }
   }
}

query getTale($id: Int!) {
   tale(id: $id) {
      ...Lore
   }
}

mutation createTale($input: CreateTaleInput!, $locations: [Int!]) {
   createTale(input: $input, locations: $locations)
}
