query getTaleDrafts($pagination: Pagination) {
   connection: taleDrafts(pagination: $pagination) {
      totalCount
      nodes {
         ...TaleSummary
      }
      pageInfo {
         ...PageInfo
      }
   }
}

query getTaleDraft($id: Int!) {
   taleDraft(id: $id) {
      ...Tale
      proposed
   }
}

mutation createTaleDraft($input: CreateTaleInput!) {
   created: createTaleDraft(input: $input) {
      id
   }
}

mutation modifyTaleDraft($id: Int!, $input: ModifyTaleInput!, $addedLocations: [Int!]!, $removedLocations: [Int!]!) {
   modified: modifyTaleDraft(id: $id, input: $input) {
      id
   }
   addedLocations: addLocationsToTaleDraft(tale: $id, locations: $addedLocations)
   removedLocations: removeLocationsFromTaleDraft(tale: $id, locations: $removedLocations)
}

mutation proposeTale($draft: Int!) {
   proposal: proposeTale(draftId: $draft)
}
