export const ICON_HOST = 'https://icons.macarena.ceo'

export const ICON_NAMESPACES = [
   'abnormals_delight',
   // 'ad_astra',
   'alexsdelight',
   'alexsmobs',
   'another_furniture',
   'archers_paradox',
   'arva',
   //   'atmospheric',
   'autumnity',
   'berry_good',
   'biomesoplenty',
   'boatload',
   'botania',
   'buzzier_bees',
   'caverns_and_chasms',
   'chimes',
   'cnb',
   'comforts',
   'compatoplenty',
   'conjurer_illager',
   'create_jetpack',
   'create',
   'createaddition',
   'createcafe',
   'culturaldelights',
   'dummmmmmy',
   'ecologics',
   'effortlessbuilding',
   'endergetic',
   'endermanoverhaul',
   'environmental',
   'etched',
   'everycomp',
   'farmersdelight',
   'farmersrespite',
   'fish_in_planks',
   'galosphere',
   'goated',
   'guardvillagers',
   'hedgehog',
   //   'hexcasting',
   'immersive_weathering',
   'incubation',
   'labels',
   'lilwings',
   'lootr',
   'map_atlases',
   'minecraft',
   'mining_helmet',
   'mysticaloaktree',
   'neapolitan',
   'origins_compat',
   'origins',
   'overweight_farming',
   'quark',
   //   'refinedstorage',
   'rootsclassic',
   'savage_and_ravage',
   'sawmill',
   'sliceanddice',
   'sullysmod',
   'supplementaries',
   //   'thermal',
   'toolbelt',
   'upgrade_aquatic',
   'v_slab_compat',
   'whisperwoods',
]
